### ISSUE TITLE
Question about "getInitialProps"

### ISSUE THREAD

**Issue by chenganma** [leerob/mastering-nextjs#37]
So I try to do this practice by using "getInitialProps"

https://github.com/leerob/mastering-nextjs/blob/main/course/navigation/03-get-initial-props/pages/post/%5Bid%5D/index.js

I am getting "Error: Post(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null."

Would you be able to provide different solution? I try what you have in the comments "getServerSideProps" but I think I still need more details. Thanks.

**Comment by leerob** [comment]
Sorry for the slow response here -> I'd always recommend `getStaticProps` or `getServerSideProps` in 98% of use cases.
